language: python
python:
  - '3.8'
dist: focal

install:
  - pip install -r mysite/requirements.txt
  - pip install awscli

script:
  - pytest mysite/polls/tests.py

env:
  global:
    - DJANGO_SETTINGS_MODULE=mysite.settings

before_deploy:
  - if [ -z "$AWS_ACCESS_KEY_ID" ]; then echo "AWS_ACCESS_KEY_ID is not set"; exit 1; fi
  - if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then echo "AWS_SECRET_ACCESS_KEY is not set"; exit 1; fi
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-west-2
  - aws sts get-caller-identity
  - aws s3 ls s3://elasticbeanstalk-us-west-2-158596392157 || echo "Failed to list S3 bucket"
  - aws elasticbeanstalk describe-environments --application-name django-tutorial || echo "Failed to describe Elastic Beanstalk environments"

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-158596392157"
  on:
    branch: main

after_deploy:
  - echo "Deployment finished. Checking S3 access again:"
  - aws s3 ls s3://elasticbeanstalk-us-west-2-158596392157 || echo "Failed to list S3 bucket after deployment"