language: python
python:
- '3.8'
dist: focal
before_install:
- sudo apt-get update
- sudo apt-get install -y sqlite3
- sqlite3 --version
install:
- pip install -r mysite/requirements.txt
script:
- pytest mysite/polls/tests.py
env:
- DJANGO_SETTINGS_MODULE=mysite.settings
services:
- sqlite3
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: 1aGrAaXP69BTI4gy//rhkOuH4UC2PF52q2QlOeHoNU+rmyBtKlMgzO4dNIDwjbSKH5jPQAABKyqGRDopYB/Qi0hFnejUVbKluzgAkWU7hjB5vgT0vXrsBzHNtUHCiDspYRf1Io0nbuUEjvm52/wwiUJXidPTz3XJUe8wppSqfGRCfbetrcgIvN1OTFX7eb1KD9IXEfO+jH55H7v4htZDpbEXPIRmdRQvxKXXbPRwKkfYyzVpk78QtruQpSqUhWDoPJpoi8i5RQzyXpILbRDX0zMiZjMiib6XYXsbUzM0SMrWrD3WVgDG646cWzYZNVLSl5VzEKWmzO8BOLXYS42xd9ajAmxQMfirky9ZOz4cdpTX6GDwA4Vqts/nqa0Fkq9pWpnAI99fThCIrw/JJ+uACYYn0PSvNj4xctwa5ShaZ3cOpAu1407sRPaoNu42zzzFKjaP+ZyPMBIoX3+P1nlKucYz4HgndxOQDls6qFXrA6ar150/xLdX8nK5rCVnn3iNhEoJ3lH1eTM2FhUDpa39vzMFH3ZIxF5SKXqCKtM7IOeOkQs6WoepcMb/EY3A6HFiqOrrK24B3d5i2a58FR0zDMz7cLCycaKAkL41cHIUKxdj4Dx7KFQC5xxqF4TxxZEHGv+Gj+xkEJ+1LNFtC75AoayloP/g0RdJ9qL5ZHhsZtA=
  secret_access_key:
    secure: levGhXeOzP6lvUtMVWe7v/AOD7WwncidduyeptWiDw+g3+Qz35X8yAzSqAGm8iONcvEpDZl2zVN8VXmggvnQjlzRLPzjTvPJ+2p6dHmCwhbn+a0k2OAod8Rg9kbu4WYztNyPLRjk41SvN+y5BeC0olQlKCQjo83UyD3mQaIaEYNN6rzKEpSPzNTDZ86Iv/MyMTcV9eGxHEVyKEmZaEqAz47JoZePvz14JZuw9BXGXmQFYrkEcZiiYDNMLmyFKdV1D32aLKCIFq2+T/Ht6rAbAhhWoJZIQO9v0IARYcDR3NH616KHD8KdX6UDWrhGITG97Fyyc3OtjrqkrPlZtZRCsx/PoZ1P1q+CgLWQ9AHHdGlJu/caf3fQfi+nJS9esffGOJa44oi09GnUCXE4oEwRp3bXYWAjnWnf6evRSe9oEB2nKtgrsgsvLknNLkM911kxboye1FvtYNvuR1fpolE+VQbW2eOLDG99uWMQ/4OjxXEapoa2xseXdcK495Y7hPY+w78fcRL8iddjcVc7oOBluvGnnNwnGVedZHzbcxUHGuQaLJYWO8TOoOM1C8njRMf7OEETCZ0q1x61BBJzQv4+DOX3KYTacV6ebMh13WqvOLUkRTDEEFmbl0B+6fJw87QalzI77zNAIL9/rULEESDswvle6vUbotq5splOBZwly4k=
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-288761742243
  on:
    branch: main
