language: python
python:
  - '3.8'
dist: focal

install:
  - pip install -r mysite/requirements.txt
  - pip install awscli

script:
  - pytest mysite/polls/tests.py

env:
  - DJANGO_SETTINGS_MODULE=mysite.settings

before_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
  - aws configure set default.region us-west-2
  - aws sts get-caller-identity
  - aws s3 ls
  - aws s3 ls s3://elasticbeanstalk-us-west-2-158596392157 || echo "Failed to list S3 bucket"
  - aws elasticbeanstalk describe-environments --application-name django-tutorial || echo "Failed to describe Elastic Beanstalk environments"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: kdP2CZfuzJB2wIOQ1RboxMjHfvxXB/Kfqe0xW3rzMogm+o+9XgCTghToWLMkpf+nvcRyz4ZDjBxc1koYeYB4aiK7tpRQDW7+57nS9k/Sb9GlwZkPHqNP+8r1DF8O+syCdz3XuCZARqmDxxMUrpA2M4RcL8hvEFjLci5OKhQabjkG82EGF8NIuU+9D1GFKN0Ehqn3YXtqcIYFrBNloLnT0DDbPhoQ/zHGlKpU8TdYsUQPkGANvb2ThcpCgIXSL9oEhggi0mIEjWfm/kUg2YT8IhqZRl0a66vXZjrEUKuxxV+mdI7Ma0NiVwJuB+E6FTXTDZtz75yqlpCXVQPapAsF+WFIWwHcXsz6MiQtkPJ9fM1goCjH0ISs4Dpdd/Q7j3w7+JSQhs/oNBJ4/lIXKSh2RpzcNiLa6SD/uTTDIdUEH8EaX63clwECShZUDJQ5ytGNrMgUuMnpX0kR4CvbvBkwhCby96QZeJqxvPN5STDTiQ+CWLzxiPHCzFijXChEbZezWv6YMRLSpmus4CTJd23MPO52pWaT2ud4+2s+vXFjQupmz8pkkj1WioZM7GA8FGo1hCAppIqSurQTrVlPW3Sm4Z3uLNk4JiJXb6iXN2T65GqLM90IoBdHA+WU+L5VyvGdngZAsHYzbcxnD7UlmeUrBAYFtlwMdQGDDHmfzl0r+XQ=
  secret_access_key:
    secure: ywaxrl+MQtdN3PuW9WR6gFygsBbhVaatuWosMoVWKLbPiBkNukNGoLx8Ktl3HOUmON97b/e4wqrJmJM2QLw7zG7J3nrr5Qi3WcMu/EvJMdQL/scLvimD7Fk89fM9aTGhoEB0mMZrM5neOuFO6imAFj2UQCbeemCJsG1QmHowoLWzOMkgHamlyyZ47RsWDZvUjGkvLJPWoShBMwoJ1dUoFcVDwL1gTz65uBeAGH25QlzmjCJGdswtkz+36bofK5JOZKmyxtI+zWn85Yx/Zs5NBnF9JPKugbl5eMQBxj4T4zlqs001shHWjijuJf7KgMd/c8WtfTF3NmimUUkj0V8IycgdKv1G5dF7YdabOAGnyn4XnsGQZkpdwugj+/Sw6z1++IlvHrH73RoEXQFx0RDMOh4eR0KQPIFxnarx1sNZWp/x70QhitbtuJvoFMQD791Z+qkK1R3huyfBQM/OOD1Qntn8D/Lm5gSSoS/qt8l7ARxmulZ5s91S6AHFatYVaWZgSs7Sjb2WVuAaggX2jdFT46A15W/r4zmKOxYbsnKhH+1f01kYLDuJF+46hfyFvOFvFyj1mx/ZeC7VkBGTUVPOETCSAeGbXhFm2GzxktRiTcmhhXGfDUi6fCB5aFthwqdPma19fur+64Rl8nNT8Yz8UJU393QLr9BMKTrvf+f9/GE=
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    branch: main

after_deploy:
  - echo "Deployment finished. Checking S3 access again:"
  - aws s3 ls s3://elasticbeanstalk-us-west-2-158596392157 || echo "Failed to list S3 bucket after deployment"