language: python
python:
- '3.8'
dist: focal
before_install:
- sudo apt-get update
- sudo apt-get install -y sqlite3
- sqlite3 --version
install:
- pip install -r mysite/requirements.txt
script:
- pytest mysite/polls/tests.py
env:
- DJANGO_SETTINGS_MODULE=mysite.settings
services:
- sqlite3
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: ArP/dAoE+vHzGQtGiJvzxjQBnTeEnTc+VvlM9/zAiBiNZAtwgzGlfiWv7oKZ9bVz9vJ1Aqz2pXiFWZZLBnItplJsTD9uCSk7kjAxVGX+DlzJrjT0fpIBSPEHR8JmyJGeHN0U/9iWET/d/mAhGbbM7RyoS2ianxC0/Z81RO3p1ZNnxjiINdLYDXF97E3xXBphqFdMGwlvj9umKJA0AFcOJsXuDRRrhChr7Gmovxs0FO5CJE+7rMr6zzMkOBVjEHE3+6ex3MsC2HO7D5LGzY1R/R5XoouUtSPgNqr1jerqPQX9dWBSyswNq+Q5hCt4p9jfDL9a+lF4qPG2/qz/wzBYBHDJvXWi7vDaina/iECGj9vn03whtuMU8Wap5z7NAkRbmHCz/rlcnCdVQdemI1DB8mgMWipnCtYqQ+M5o26LUCiSXi3lDikCjNv/AFyR6Lq3dVkiARlT6E5tfL0qL2OgC3cusmZ8HTcw/WPlT3HUcvJNle2xTcpDflFPLywwpiZD5o+hC6fzmBW+5em0no2I7li+/gaaF+S668ldv9zHvmx04weEF3HGMekX1nsX49pTFXwkD32FNsYh/2TDwG6LxLHXupZUUwFCE+XfafB/IeqooOcSGsY10sHJ2HY8xeoqrOFpdJ5xqXEjk88V51jKvNOYhPSthzhKyC45d5BZPKI=
  secret_access_key:
    secure: AfJByeTCzzmh9882UHaqYFoQa7MQaNOB6CutiQ92uj53J5pbkTR2FfWrfkJShsyc2ceY21ynOFCJL+e9q2QMpK6iAHmNOGArwExrmfgoxadw34gSEGMqPvs83z6Q1E2URyBjg9RNj0rDnEwkTjMYnR0Wr5oPO20COHhUqaigWgUK/xEX72YY4AKlR7w3hXUFaiq/eCUrAilR4UNPj6O5Hy6EaYXvlyx96snN5443X8OwSWr90Fp4D5z51bCVW8uRPih/hp/z7KJ6ZzzL3qCETaKz/eUPM05GHBsihLO8QvE++dmsyqmS8ZkQFXXnoH61O5SV9e4Yhndw2benpqfrIgVKb1Nsgzmt4lx12E7UmBkXKxLaKJBZJ7gsUr8GXACtwgQkBSxmBuoza8jhJGcAEEbFV7CcNspg151KRM/Z914H/aPaw9WTlCfCqQwQh8jXUDFissWlqDz37BzFRK6PycKnr4wsMPRWJS1sh9L4zR59TQx8em81haGs7a1EXPSEIrlS7kkl0JCkFIBL+p5atkK5AHyIUI2abzdN/aasfeZ0Cnn7w+wnehUJ9ZGpMvk8x0Z0Xd2jZbDnH/mHsW0qY45qdstl8cq2duZm3jldQR7zUalXmjdqxNeQ54I8XxWH22LpaHs4op/R2PGqxV7JJO3aieT3wwOXi/NADHIxAqc=
  region: us-west-2
  app: django-tutorial
  env: django-env
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    branch: main
