language: python
python:
- '3.8'
dist: focal
before_install:
- sudo apt-get update
- sudo apt-get install -y sqlite3
- sqlite3 --version
install:
- pip install -r mysite/requirements.txt
script:
- pytest mysite/polls/tests.py
env:
- DJANGO_SETTINGS_MODULE=mysite.settings
services:
- sqlite3

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: O9FCitES9yVMdlx+NZn+igc4zQAn82QAuUIe0eyeYMtV3rfDzqaaCR/z3OWg2YVrSyqm5kDljQTqz4+Hrhf0LvazGXw9vbtbxRnEe+r14vT/7xY548KGnGm0Pmd4BOEvPLvbXnyzUPtfdhELqpzFx/J7ZtEg+zYpq/nx+VOHzUmiR8jq52vCDQwvy2Ou+f/01qQgbCLtE4qL69Q/UIEqaa789oetmD51gnF02B76HEpqBR5YJKd9oVunuYoH7LKG+PZP4HP8kubcxUAvP1WEIaA9HFrCr4eY44qjnXuCqN4qdQzWhGIhrUSejWReh8LoHRcLY6K7prE1p+bUEe+4hoyqVR1ceVDWFtR0BUosrVrKd/iceiCZ3SH11x3OcuW0KujmNKAveXIrHU/WY1eWluITWuUVp90mNgZZFjqCNM62sWOwrnmkpICX/VzaD9W7Me9aj1u55SHo1vmamAH516JOF722iHEkwlVZWJOkNeoICuhrBmpF8ES+ycFkrx9BvK+JHj8Bn4xu+kjh0JZSSETcC26uLytRRCibCh73bf9SSj71VDc34iYvHWu76hEtawhJpbzP7vco7oEo2I974QYv85t9v0+Oc94MirpSePu4kN50ec2n3ekmQjwBSpRgBEabbWn9g7u4RLNRi2rQM+VikeBdqJ6SKAZMQJnuoSc=
  secret_access_key:
    secure: Iarg+EiSfaelHnJEDLD0fgYEN9CskxUglX4b5fqPJmk8BOarP220k9IEF0NnOLfJsTjSEA4d4FJTy6JSLAouNwC4EPsGPxHIDPRRH6qA6uYi++0S9FHHrmG4sDep/DEwIbbSzR1s/m/wnFzS9cnGbtlMGeJGwYKCMiPcgeLDO2kGbrJs0+yeUwPFmWuTkW70MnVmo0xx94RLpY/oZEiTdd2yOQr/8dUXnmstUAyUisd7q+xb21sYtj5AVrm/T9gnclpS++WiAq/2Tg2LdwVDVazYG9w7apePCNpNKICV4DZLrlnRk8Pn8YwJBWuaTCJAElwSCqHPxTidK+hlYQHzNwSAO+UnnXEDwirwb2Tr0UZ5aQypy+7zAtfEZzr4IvpSI6NbYiyqrytvrd+UjWtDBZj4LOmgXju5xIJBhCuj4uHbD1khzKLjVdDMgSKOdzCdgYYcH1JC1zIoD/mn2RNtzTWNKOmVQcJRIu/3Gt0OXb4RrADJmjcf6VLdaF5p1yfvbhBcR1PI19FtvJeYFvZSkuPrB927ucC+oS+srETa1Djm5jcaJruQX2mkk44rL7FC+QTJDhiEkNiIHTqzWHwuKhG7iFFT57D4CsxHpoPIo/W1mIQftYH4w5ETgqLRmgOvPWH9RmveiMb4Z91pELe2mlnK5yKsFollrnitdlWoyUs=
  region: "us-east-2"
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-158596392157"
  on:
    branch: main