     language: python
     python:
       - "3.8"  # Specify the Python version
     install:
       - pip install -r mysite/requirements.txt  # Install dependencies
     script:
       - pytest mysite/polls/tests.py
     env:
       - DJANGO_SETTINGS_MODULE=mysite.settings
