language: python
python:
- '3.8'
dist: focal
before_install:
- sudo apt-get update
- sudo apt-get install -y sqlite3
- sqlite3 --version
install:
- pip install -r mysite/requirements.txt
script:
- pytest mysite/polls/tests.py
env:
- DJANGO_SETTINGS_MODULE=mysite.settings
services:
- sqlite3
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: your-bucket-name
  region: us-west-2
  bucket_name: elasticbeanstalk-us-west-2-158596392157
  on:
    branch: main
